ALTER TABLE users ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS postal_code VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS country VARCHAR(2) DEFAULT 'US';
